# Generated by Django 5.2.9 on 2026-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('password', models.CharField(db_column='PasswordHash', max_length=500)),
                ('role', models.CharField(db_column='Role', max_length=50)),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='UserId')),
                ('token', models.CharField(db_column='Token', max_length=500)),
                ('expires_at', models.DateTimeField(db_column='ExpiresAt')),
                ('created_at', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'RefreshTokens',
                'managed': False,
            },
        ),
    ]
