# Generated by Django 5.2.9 on 2026-01-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=150)),
                ('email', models.EmailField(db_column='Email', max_length=255)),
                ('role', models.CharField(db_column='Role', max_length=50)),
                ('is_superuser', models.BooleanField(db_column='IsSuperUser')),
                ('last_login', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
